version: '2'
services:
  api_server:
    build: .
    hostname: api_server
    ports:
      - "8080:9292"
    links:
      - mysql
    env_file:
      - .env
    command: /run.sh
  mysql:
    image: mysql:5.6
    environment:
       MYSQL_DATABASE: 'api_server'
       MYSQL_ROOT_PASSWORD: 'topsecret'
