source 'https://rubygems.org'
ruby "2.3.1"

gem 'rack-cors'
gem 'mysql2', '0.3.18'
gem 'sqlite3'
gem 'activerecord', '~> 4.2.0', :require => 'active_record'
gem 'hashie-forbidden_attributes'
gem 'honeybadger', '~> 1.16.7'
gem 'json'
gem 'napa', '0.5.0'
gem 'roar', '~> 0.12.0'
gem 'grape-swagger'
gem 'grape-entity'
gem 'thin'
gem 'rack'
gem 'rake'

group :development,:test do
  gem 'pry'
end

group :development do
  gem 'rubocop', require: false
  gem 'shotgun', require: false
end

group :test do
  gem 'factory_girl'
  gem 'rspec'
  gem 'rack-test'
  gem 'simplecov'
  gem 'webmock'
  gem 'database_cleaner'
end
